[build]
  base = "website"
  publish = "_site"
  command = "bundle install && bundle exec jekyll build"
  ignore = "if [ \"$BRANCH\" != \"main\" ]; then echo 'Skipping non-main branch'; exit 0; else exit 1; fi"

[build.environment]
  RUBY_VERSION = "3.2"
