name: BearMinder
options:
  minimumXcodeGenVersion: 2.35.0

packages:
  BearMinderCore:
    path: ../..

targets:
  BearMinder:
    type: application
    platform: macOS
    deploymentTarget: "12.0"
    sources:
      - path: ../../AppTemplate
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.yourdomain.BearMinder
        CODE_SIGN_IDENTITY: "-"
        INFOPLIST_FILE: Info.plist
    dependencies:
      - package: BearMinderCore
        product: BearMinderCore

schemes:
  BearMinder:
    shared: true
    build:
      targets:
        BearMinder: all
    run:
      config: Debug
